### ISSUE TITLE
vim mode support

### ISSUE THREAD

**Issue by xp12047** [zurex/mote#51]
I feel the need to consider supporting vim mode.  Also no compiled windows binaries?

**Comment by zurex** [comment]
@xp12047  we do support windows version, you could build it by yourself. We plan to release the official version in October.
For vim mode, it should be support after plugin system released

**Comment by xp12047** [comment]
> @xp12047 我们确实支持 windows 版本，您可以自己构建它。我们计划在 10 月发布正式版本。 vim模式需要插件系统发布后支持
Okay, thank you
